### ISSUE TITLE
Лишняя переменная

### ISSUE THREAD

**Issue by goncharov89** [Alexe22/Test_api#4]
code = request_res.status_code

Ты с кодом потом явно ничего не делаешь, думаю лучше использовать

if request_res.status_code == 200

**Comment by goncharov89** [comment]
используя лишние переменные теряется семантика в коде.

**Comment by goncharov89** [comment]
и ты делаешь так ниже в коде:
if response_order.status_code == 200:

**Comment by Alexe22** [comment]
переменную удалил
